name: IslandRate
main: com.yovez.islandrate.IslandRate
version: 1.3.4.2
author: Yovez
depend: [ASkyBlock]
softdepend: [PlaceholderAPI]
commands:
    rate:
        description: Rate the island you are at!
